- documentation/Remove-PnPTeamsUser.md
Update of the second example to use the _Role_ parameter
> Remove-PnPTeamsUser - Update example 2

- src/Commands/Model/AzureApp.cs
> Added permission scope MSGraph.Directory.ReadWrite.All

- CHANGELOG.md
- documentation/Get-PnPSubWebs.md
- src/Commands/Web/GetSubwebs.cs
N/A
Bringing fix of https://github.com/pnp/PnP-PowerShell/pull/3011 into this repository
> Copy of PR3011 from PnP PowerShell

- samples/Connect.AzureAutomation/Deploy-AzureAppOnly.ps1
- samples/Connect.AzureAutomation/Deploy-AzureAutomation.ps1
- samples/Connect.AzureAutomation/Deploy-FullAutomation.ps1
- samples/Connect.AzureAutomation/Readme.md
- samples/Connect.AzureAutomation/test-connection-runbook.ps1
Similar to the previous repo but updated with the new cmdlets and modules: Connecting to O365 with PnP PowerShell using App Only Certificate using the PnP.PowerShell module sample.
> Sample for Azure Automation

- README.md
Updated with the return of the -UseWebLogin
Updated README.md
Following the return of ```-UseWebLogin```, I've updated the README file
> Updated -UseWebLogin available on Windows

- documentation/Remove-PnPTermGroup.md
- src/Commands/Taxonomy/RemoveTermGroup.cs
NA
Added missing Force parameter for `Remove-PnPTermGroup` command.
Localization string message improved.
Added necessary changes in docs
> Added missing Force parameter for Remove-TermGroup

- src/Commands/Base/ConnectOnline.cs
NA
Added missing `ReturnConnection` for weblogin scenario
> Fix - missing return connection for Web Login scenario

- documentation/Get-PnPListPermissions.md
None
Updated example 2 in Get-PnPListPermissions (typo)
> Get-PnPListPermissions - Updated example 2

- documentation/Get-PnPAppInfo.md
None
Updated example 2 with ```-ProductId``` instead of ```-Identity```
> Updated -ProductId parameter in example 2

- documentation/Add-PnPPlannerBucket.md
- documentation/Add-PnPPlannerTask.md
- documentation/Get-PnPPlannerBucket.md
- documentation/Get-PnPPlannerPlan.md
- documentation/Get-PnPPlannerTask.md
- documentation/New-PnPPlannerPlan.md
- documentation/Remove-PnPPlannerBucket.md
- documentation/Remove-PnPPlannerPlan.md
- documentation/Remove-PnPPlannerTask.md
- documentation/Set-PnPPlannerBucket.md
- documentation/Set-PnPPlannerPlan.md
- documentation/Set-PnPPlannerTask.md
Updated all PnP Planner documentation pages to include Required Microsoft Graph Permissions and changed group parameters to accept group name and id.
> Planner Documentation Updates - Adding Required Permissions 

- documentation/Add-PnPTeamsTab.md
- documentation/Add-PnPTeamsUser.md
- documentation/Get-PnPTeamsChannel.md
- documentation/Get-PnPTeamsChannelMessage.md
- documentation/Get-PnPTeamsTeam.md
- documentation/Get-PnPTeamsUser.md
- documentation/New-PnPTeamsTeam.md
- documentation/Remove-PnPTeamsApp.md
- documentation/Remove-PnPTeamsChannel.md
- documentation/Remove-PnPTeamsTab.md
- documentation/Remove-PnPTeamsTeam.md
- documentation/Remove-PnPTeamsUser.md
- documentation/Set-PnPTeamsChannel.md
- documentation/Set-PnPTeamsTab.md
- documentation/Set-PnPTeamsTeamArchivedState.md
Several more Teams documentation fixes:
- Fixes to denote id, mailnickname or display name can be used for team
- Channel id or channel display name
- Correcting and adding examples
Thanks
> Teams Documentation - Fixes

- documentation/Add-PnPMicrosoft365GroupOwner.md
- documentation/Add-PnPSiteClassification.md
- documentation/Clear-PnPMicrosoft365GroupMember.md
- documentation/Enable-PnPSiteClassification.md
- documentation/Get-PnPGraphAccessToken.md
- documentation/Get-PnPGraphSubscription.md
- documentation/Get-PnPMicrosoft365Group.md
- documentation/Get-PnPMicrosoft365GroupMembers.md
- documentation/Remove-PnPDeletedMicrosoft365Group.md
- documentation/Remove-PnPSiteClassification.md
- documentation/Reset-PnPMicrosoft365GroupExpiration.md
- documentation/Set-PnPMicrosoft365Group.md
Various typo fixes for Graph commands and examples
> Graph Documentation Fixes

- documentation/Set-PnPTeamsTeam.md
Corrected example command and added extra examples.
> Set-PnPTeamsTeam Documentation Update

- documentation/Add-PnPSiteCollectionTermStore.md
- documentation/Get-PnPSiteCollectionTermStore.md
- documentation/New-PnPSiteCollectionTermStore.md
- documentation/Remove-PnPSiteCollectionTermStore.md
- src/Commands/Taxonomy/NewSiteCollectionTermStore.cs
- src/Commands/Taxonomy/RemoveSiteCollectionTermStore.cs
N/A
Added new cmdlets for working with the site collection term store
Add-PnPSiteCollectionTermStore
Get-PnPSiteCollectionTermStore
Remove-PnPSiteCollectionTermStore
> Added cmdlets for working with the site collection term store

- documentation/Add-PnPMicrosoft365GroupToSite.md
N/A
Fixing documentation on Add-PnPMicrosoft365GroupToSite
> Fixing documentation on Add-PnPMicrosoft365GroupToSite

- pages/articles/upgrading.md
Removing -AllowPrerelease from upgrading.md article page
> Update upgrading.md : removing -AllowPrerelease

- samples/Connect.AzureAutomation/Deploy-AzureAppOnly.ps1
- samples/Connect.AzureAutomation/Deploy-AzureAutomation.ps1
- samples/Connect.AzureAutomation/Deploy-FullAutomation.ps1
- samples/Connect.AzureAutomation/Readme.md
- samples/Connect.AzureAutomation/test-connection-runbook.ps1
Related to issue #157 
Contains the following fixes:
- Updated to use GA version 1.2
- Fixed runbook issue to align with the change in which certificates are consumed
- Use securestring to gather passwords
- Updated full script to include the subscription id
- Minor updates to Readme.md
> Updated sample with changes and fixes

- documentation/Convert-PnPSiteTemplateToMarkdown.md
- documentation/Get-PnPSiteUserInvitations.md
- documentation/Get-PnPStructuralNavigationCacheSiteState.md
- documentation/Get-PnPStructuralNavigationCacheWebState.md
- documentation/Unregister-PnPHubSite.md
Fixed a few more typos in the documentation - inccorect commands or formatting issues.
> Fixing Typos in documentation

- src/Commands/Site/SetSite.cs
- src/Commands/Teams/SetTeamsChannel.cs
Fixes #229 , #227 
Fixes issues #229 and #227 
For #229 - correct the membership type check to "standard" as per docs here - https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0
For #227 - renamed it as mentioned by Todd in the issue.
> Fix #229, #227 issues

- pages/articles/index.md
> fixed typo

- documentation/Add-PnPSiteScriptPackage.md
- documentation/Set-PnPSiteScriptPackage.md
N/A
The `Add-PnPSiteScriptPackage` and `Set-PnPSiteScriptPackage` cmdlets were lacking documentation. Adding it in this PR.
> Adding documentation on SiteScriptPackage cmdlets

- documentation/Get-PnPTemporarilyDisableAppBar.md
- documentation/Set-PnPTemporarilyDisableAppBar.md
- src/Commands/Admin/GetTemporarilyDisableAppBar.cs
- src/Commands/Admin/SetTemporarilyDisableAppBar.cs
N/A
Adds `Set-PnPTemporarilyDisableAppBar` and `Get-PnPTemporarilyDisableAppBar` cmdlets which are yet to be released in the next SharePoint Online Management Module release.
More info on the cmdlet here:
https://docs.microsoft.com/en-us/SharePoint/sharepoint-app-bar#temporarily-disable-the-sharepoint-app-bar
> Added TemporarilyDisableAppBar cmdlets

- pages/articles/authentication.md
Fix spelling of 'crednetials' to 'credentials'.
Fixed spelling in documentation
> Fix spelling on authentication.md

- documentation/Get-PnPTemporarilyDisableAppBar.md
None
Fixed documentation for Get-PnPTemporarilyDisableAppBar
> fixed documentation for Get-PnPTemporarilyDisableAppBar.md

- documentation/Remove-PnPHubSiteAssociation.md
Fixed wording of Remove-PnPHubSiteAssociation command.
> Updating documentation - Remove-PnPHubSiteAssociation

- src/Commands/Admin/SetTenantSite.cs
Hi,
Fixed an issue with setting ConditionalAccessPolicy bug as specified here - https://github.com/pnp/powershell/issues/231
- [ X] Bug Fix
#231
> Fixed the bug with setting the ConditionalAccessPolicy using Set-PnPTenantSite

- documentation/Set-PnPTerm.md
None
Updated the Set-PnPTerm documentation
> Updated Set-PnPTerm.md

- pages/articles/authentication.md
N/A
Updated Register-PnPAzureADApp sample to use a result variable for easier access to the base64 encoded output. Also added quotes around the name to show spaces are allowed in the naming.
> Updated Register-PnPAzureADApp sample to use a result variable

- src/Commands/Teams/GetTeamsTeam.cs
> Fix #423 - Error action for teams team

- src/Commands/Microsoft365Groups/NewMicrosoft365Group.cs
- src/Commands/Utilities/Microsoft365GroupsUtility.cs
> Fix #422 - Create team issue with New-PnPMicrosoft365Group cmdlet

- src/Commands/Admin/RemoveTenantSite.cs
Fixes #441 
Added `FromRecycleBin` parameter to delete site from recycle bin.
> Feature #441 - Added from recycle bin parameter

- pages/articles/connecting.md
> Updated typo in connecting.md

- documentation/Get-PnPSubscribeSharePointNewsDigest.md
- documentation/Set-PnPSubscribeSharePointNewsDigest.md
N/A
Minor fixes in the documentation of the *-PnPSubscribeSharePointNewsDigest cmdlets
> Fixes in the documentation of the PnPSubscribeSharePointNewsDigest cmdlets

- documentation/New-PnPTeamsTeam.md
N/A
Clarified that the New-PnPTeamsTeam cmdlet can be used to teamify and to create a new Teams team
> Updated documentation on New-PnPTeamsTeam

- src/Commands/Provisioning/Site/AddDataRowsToSiteTemplate.cs
Fixes #518
Ensure correct initialization of web and site properties
> Fix #518 - ensure correct initialization for web and site properties

- src/Commands/Teams/AddTeamsTab.cs
Fixes #499
Returns value for newly added tab
> Fix #499 - return value for newly added tab

- src/Commands/Fields/AddField.cs
Fixes #501 
Return the added field value
> Fix #501 - Return Add-PnPField value

- documentation/Add-PnPTeamsTab.md
None
Updated documentation for Add-PnPTeamsTab
> Updated Add-PnPTeamsTab documentation

- src/Commands/Files/AddFile.cs
Fixes #533 
Fixes #533, we only need to provide folder
> Fix #533 - set content type while uploading files

- src/Commands/Fields/AddTaxonomyField.cs
Fixes #434 
Added support for field options while creating Taxonomy fields
> Fix #434 - support field options for taxonomy fields

- src/Commands/Taxonomy/SetTerm.cs
Fixes #555 
Set local custom properties instead of Shared properties.
> Fix #555 - Set local custom properties

- src/Commands/Teams/SetTeamsTeam.cs
Fixes #572, #593
Fix #572 , #593 , only update visibility if specified
> Fix #572 - group visibility fixes

- src/Commands/Apps/AddApp.cs
- src/Commands/Apps/GetApp.cs
- src/Commands/Apps/InstallApp.cs
- src/Commands/Apps/PublishApp.cs
- src/Commands/Apps/RemoveApp.cs
- src/Commands/Apps/UninstallApp.cs
- src/Commands/Apps/UnpublishApp.cs
- src/Commands/Apps/UpdateApp.cs
NA
Added ValueFromPipeline=true for App cmdlet's scope parameter.
> Fix: Added ValueFromPipeline to true for App cmdlet's scope parameter

- src/Commands/Admin/SetTenant.cs
- src/Commands/Model/SPOTenant.cs
None
Added support for tenant setting MarkNewFilesSensitiveByDefault
> Add support for tenant MarkNewFilesSensitiveByDefault

- documentation/Set-PnPTenantSite.md
Updated Set-PnPTenantSite.md  documentation Example 1 command  (from -Sharing to -SharingCapability) as -Sharing is not valid option anymore
This is my first Pull request, so Please excuse me If I have done it in wrong way/place.
This is a very small documentation update. Updated  Set-PnPTenantSite.md  documentation Example 1 command  (from 
-Sharing to -SharingCapability) as -Sharing is not valid option anymore
> Updated Set-PnPTenantSite.md

- documentation/Set-PnPTenantCdnPolicy.md
none
Added example to set ExcludeRestrictedSiteClassifications policy based on example in documentation of [Set-SPOTenantCdnPolicy](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantCdnPolicy.md)
> Added example to set ExcludeRestrictedSiteClassifications policy

- documentation/Set-PnPTenant.md
None
The old link are no longer in use. I updated it to the new documentation page.
> Updated SharingCapability link

- documentation/Connect-PnPOnline.md
https://github.com/pnp/powershell/issues/534
Adds CurrentCredentials parameter description in Connect-PnPOnline.md
> CurrentCredentials Parameter Description

- documentation/New-PnPAzureCertificate.md
N/A.
Replace URL leading to sample configuration. Old URL led to an archived repository.
> fix(new-pnpazurecertificate) Update sample doc URL

- documentation/Set-PnPSearchSettings.md
Updated description of `-SearchBoxPlaceholderText` parameter & some minor fixes.
>  Updated description of "-SearchBoxPlaceholderText" parameter

- documentation/Get-PnPTenantDeletedSite.md
- documentation/Remove-PnPTenantDeletedSite.md
- documentation/Restore-PnPTenantDeletedSite.md
- src/Commands/Admin/GetTenantDeletedSite.cs
- src/Commands/Admin/RemoveTenantDeletedSite.cs
- src/Commands/Admin/RestoreTenantSite.cs
- src/Commands/Model/SPODeletedSite.cs
- src/Commands/Utilities/UrlUtilities.cs
Fixes #871 
Added commands 
1) Get-PnPTenantDeletedSite
2) Restore-PnPTenantSite
3) Remove-PnPTenantDeletedSite
> #871 - added commands to fetch,restore and delete tenant sites

- src/Commands/Site/SetSite.cs
Fixes #817 
Fixed issue setting site logo for modern sites
> Fix #817 - site logo update changes

- documentation/Set-PnPHubSite.md
- src/Commands/Admin/SetHubSite.cs
Fixes #829 
Added support to sync hub site permissions to associated site.
> #829 - Additional hub site properties

- src/Commands/PnP.PowerShell.csproj
Downgraded .NET dependencies to handle Az DLLs issues
> Downgraded dependencies to handle Az DLLs

- pages/articles/credentialmanagement.md
- [x ] Grammar
Clean up grammar
Clean up grammar
> Cleaning up grammar

- documentation/Get-PnPUnifiedAuditLog.md
Starttime needs to be before endtime in the timeline to get the audit logs.
Get-PnPUnifiedAuditLog -ContentType SharePoint -StartTime (Get-Date).AddDays(-1) -EndTime (Get-Date).AddDays(-2)
Starttime: Yesterday
Endtime: Day before yesterday
Needs to be
Get-PnPUnifiedAuditLog -ContentType SharePoint -StartTime (Get-Date).AddDays(-2) -EndTime (Get-Date).AddDays(-1)
Starttime: Day before yesterday
Endtime: Yesterday
* *Please update this PR information accordingly. We use this as …
> Change starttime and endtime

- documentation/Get-PnPHubSite.md
- documentation/Grant-PnPHubSiteRights.md
- documentation/Revoke-PnPHubSiteRights.md
Tidying up some of the PnPHubSite commands to fix missing sections of documentation and to add further examples
> *PnPHubSite documentation fixes

- documentation/Get-PnPPlannerTask.md
Changed "Example 3" as -Group and -PlanId parameters cannot be used together
- Documentation fix
Documentation issue for Example 3
Correcting Documentation Example 3
> Update Get-PnPPlannerTask.md Example 3

- src/Commands/ManagementApi/GetUnifiedAuditLog.cs
Issue #669
Changed 12 hour clock (hh) to 24 hour clock (HH) in `Get-PnPUnifiedAuditLog` to address issue #669
> Changed time formatting from 12 hour clock to 24 hour clock for Get-PnPUnifiedAuditLog

- documentation/Get-PnPFileVersion.md
Added text to include that the cmdlet does not return the current version of the file. Also added how to get that information. While I was in there I added another example because everyone likes more examples. Unless we're talking about Connect-PnPOnline, then maybe we'd like a few fewer examples. :)
Puts [issue 1098](https://github.com/pnp/powershell/issues/1098#issuecomment-924046933) to bed. 
A couple of small changes to the description and synopsis.
> Added help and example

- documentation/Add-PnPSiteCollectionAppCatalog.md
- src/Commands/Admin/AddSiteCollectionAppCatalog.cs
N/A
Made Site parameter optional, will take currently connected to site when not provided, added trailing slash trimming from URL to avoid weird error if trailing slash added, made Site parameter position 0 parameter so the URL can also be passed in without explicitly providing -Site making it more intuitive to use
> Updates to Add-PnPSiteCollectionAppCatalog

- documentation/Get-PnPFolderItem.md
Removed extra square brackets from Syntax. Removed a full stop from PARAMETERS Connection to make it look consistent to all others.
> Removed extra brackets and a full stop

- src/Commands/Utilities/REST/RestResultCollection.cs
Issue #617 
Fixed `Get-PnPFlow` not returning all Flows
> Fixed issue with nextLink not getting followed up on for Get-PnPFlow

- documentation/Enable-PnPCommSite.md
Removed extra square brackets from Syntax section, -DesignPackageId was surrounded by extra brackets. 
Added full stop in the PARAMETERS section's sentence of -DesignPackageId.
> Removed extra brackets, and addition of full stop.

- documentation/Set-PnPRoleDefinition.md
- src/Commands/Site/SetRoleDefinition.cs
Added Set-PnPRoleDefinition cmdlet allows you to set an existing role definition (permission level) in a site collection
> Added Set-PnPRoleDefinition cmdlet

- documentation/Get-PnPAccessToken.md
- documentation/Get-PnPAppAuthAccessToken.md
Issue #909 
Updated documentation to make the difference between Get-PnPAccessToken and Get-PnPAppAuthAccessToken more clear
> Updated documentation on Get-PnPAccessToken and Get-PnPAppAuthAccessToken

- documentation/Add-PnPListItem.md
Issue #806 
Adding documentation on the numeric notation that needs to be provided
> Updated documentation on Add-PnPListItem for numeric values

- documentation/Get-PnPTeamsChannelMessage.md
No issues
Description of the ```Get-PnPTeamsChannelMessage``` should include say "get", not "send".
> Fixed cmdlet description

- documentation/Get-PnPTenantRecycleBinItem.md
I might be wrong, but felt adding "Connect-PnPOnline" command before Url to make better understanding. For a beginner it might be confusing having just a Url above the actual command. You guys are better judge :)
> Added Connect-PnPOnline command before Url

- CHANGELOG.md
- documentation/Get-PnPSiteScriptFromWeb.md
- src/Commands/PnP.PowerShell.csproj
- src/Commands/SiteDesigns/GetSiteScriptFromWeb.cs
Fixes issue #869
Fixed paramsets, made Url optional, updated documentation
> Fixes to Get-PnPSiteScriptFromWeb

- CHANGELOG.md
- src/Commands/Base/GetChangeLog.cs
N/A
Fixed the regular expression for `Get-PnPCangeLog -Nightly` so it returns output again
> Fixed Get-PnPChangeLog -Nightly

- CHANGELOG.md
- documentation/New-PnPUPABulkImportJob.md
- src/Commands/UserProfiles/NewUPABulkImportJob.cs
Added the option to provide a url to an existing file in SharePoint to submit a new user profile bulk import job via New-PnPUPABulkImportJob.
> Add url parameter to New-PnPUPABulkImportJob

- CHANGELOG.md
- documentation/Get-PnPSiteScriptFromWeb.md
- src/Commands/Base/PipeBinds/TenantSiteDesignPipeBind.cs
- src/Commands/SiteDesigns/GetSiteScriptFromWeb.cs
- src/Commands/SiteDesigns/RemoveSiteDesign.cs
N/A
Fixing bug in Get-PnPSiteScriptFromWeb and Remove-PnPSiteDesign
> Fixing bugs in Get-PnPSiteScriptFromWeb and Remove-PnPSiteDesign

- documentation/Add-PnPSiteDesign.md
- documentation/Add-PnPSiteScript.md
Answers https://github.com/pnp/powershell/issues/1197
Updated documentation to clarify how to provide a preview image
> Updated documentation on site designs

- CHANGELOG.md
- documentation/New-PnPSite.md
- documentation/New-PnPTenantSite.md
> PR1207 resubmit

- documentation/Remove-PnPWeb.md
Updated example 3. As we're going to use Get-PnPSubWeb (singular) in future versions.
> Updated example 3 of `Remove-PnPWeb`

- CHANGELOG.md
- documentation/Add-PnPEventReceiver.md
- documentation/Get-PnPEventReceiver.md
- documentation/Remove-PnPEventReceiver.md
- src/Commands/Base/PipeBinds/EventReceiverPipeBind.cs
- src/Commands/Enums/EventReceiverScope.cs
- src/Commands/Events/AddEventReceiver.cs
- src/Commands/Events/GetEventReceiver.cs
- src/Commands/Events/RemoveEventReceiver.cs
Fixed version of PR #250 
Added Scope parameter to Get/Add/Remove-PnPEventReceiver
> Added Scope parameter to Get/Add/Remove-PnPEventReceiver

- src/Commands/Utilities/VersionChecker.cs
N/A
Removed extra space in update warning
> Removed extra space in update warning

- CHANGELOG.md
- src/Commands/Utilities/ListItemHelper.cs
Fixes #928 
Fixed issue with setting Modified date value when using `Batch` parameter
> Fix #928 - issue with setting Modified date in Batch

- CHANGELOG.md
- src/Commands/Utilities/ListItemHelper.cs
Fixes #921 
Fixed issue with Taxonomy Item in a batch request.
> Fix #921 - issue with Taxonomy field in batch request

- CHANGELOG.md
- documentation/Add-PnPPage.md
- documentation/Set-PnPPage.md
- src/Commands/Pages/AddPage.cs
- src/Commands/Pages/SetPage.cs
NA
1) Adds ability to demote a news post to a normal page
2) Adds ability to create multilingual pages in `Add-PnPPage` and `Set-PnPPage` cmdlets.
> Feature - multilingual pages support, demote page

- documentation/Remove-PnPList.md
The switch Title does not work. The switch -Identity is correct as referenced in Example 1 and 2
> Correct Example 3 switch

- CHANGELOG.md
- documentation/Get-PnPMasterPage.md
Updated Get-PnPMasterPage to add an example as it was missing.
> Update Get-PnPMasterPage - added example

- CHANGELOG.md
- documentation/Set-PnPTenant.md
- src/Commands/Admin/SetTenant.cs
- src/Commands/Model/SPOTenant.cs
Fixes #1323 
Added `DisableAddToOneDrive` to Get/Set PnPTenant cmdlet
> #1323 - Added DisableAddToOneDrive to Get/Set PnPTenant cmdlet

- CHANGELOG.md
- documentation/Add-PnPSiteDesign.md
The old text was:
"Specifies if the site design is a default site design" 
The text imples that a value should be added after -IsDefault. e.g. "-IsDefault $true"
My change of "if" to "that" makes the text clearer.
"Specifies if the site design is a default site design"
* **Please target your PR to Dev branch. If you do not target the Dev branch we will not …
> Clarification to the -IsDefault parameter

- documentation/Get-PnPTenantCdnPolicies.md
- documentation/Remove-PnPTenantSyncClientRestriction.md
- documentation/Set-PnPTenantCdnEnabled.md
Minor updates to Get-PnPTenantCdnPolicies (replace incorrect command description). 
Updated Set-PnPTenantCdnEnabled.md to correct description spelling, provide additional examples and include description of the -NoDefaultOrigins Parameter.
> Update Get-PnPTenantCdnPolicies.md and Set-PnPTenantCdnEnabled.md

- CHANGELOG.md
- documentation/Add-PnPSiteDesign.md
- documentation/Add-PnPSiteDesignFromWeb.md
- documentation/Set-PnPSiteDesign.md
- src/Commands/Enums/SiteWebTemplate.cs
- src/Commands/SiteDesigns/SetSiteDesign.cs
Include new 'ChannelSite' for ID=69 
https://github.com/pnp/powershell/issues/1358
And - wrong text for Thumbail Url
> Fixed Text for page/info

- documentation/Add-PnPTenantTheme.md
Updated Add-PnPTenantTheme to add overwrite commentary and added example
> Update Add-PnPTenantTheme.md to add Overwrite text and example

- pages/articles/installation.md
N/A
Added instructions on how to install the prerelease
> Added instructions on how to install the prerelease

- documentation/Update-PnPUserType.md
> Fixed synopsis section of Update-PnPUserType

- CHANGELOG.md
- src/Commands/Web/GetSubweb.cs
N/A
Removing alias on `Get-PnPSubWeb` for `Get-PnPSubWebs`
> Removing alias on `Get-PnPSubWeb` for `Get-PnPSubWebs`

- documentation/Set-PnPTenant.md
N/A
Fixing errors on AllowFilesWithKeepLabelToBeDeletedODB and AllowFilesWithKeepLabelToBeDeletedSPO
> Fixing documentation errors on `AllowFilesWithKeepLabelToBeDeletedODB/SPO`

- documentation/Get-PnPTaxonomyItem.md
- documentation/Get-PnPTerm.md
- Fixed parameters no longer available and added example in Get-PnPTaxonomyItem
- Fixed example typo -Include to -Includes in Get-PnPTerm
> Get-PnPTaxonomyItem & Get-PnPTerm Documentation Updates

- documentation/Add-PnPField.md
None
Update documentation of Add-PnPField with -AddToAllContentTypes parameter.
Fun fact: I couldn't find this parameter in the documentation but I was pretty sure it existed. After a big of digging it turned out that I created the PR last year to add the parameter https://github.com/pnp/PnP-PowerShell/pull/2909 😄
> Update documentation of Add-PnPField with -AddToAllContentTypes parameter

- CHANGELOG.md
- documentation/Set-PnPTenant.md
- src/Commands/Admin/SetTenant.cs
- src/Commands/Model/SPOTenant.cs
NA
Added capability to enable/disable Fluid components in the Tenant
> Feature: Added capability to enable/disable fluid components

- documentation/Get-PnPSearchConfiguration.md
- src/Commands/Search/GetSearchConfiguration.cs
- src/Commands/Utilities/REST/RestHelper.cs
Added support to call REST endpoint to fetch promoted results defined via query rules and output them in Bookmark supported CSV format.
> Support export promoted results to Bookmarks compatible CSV file

- documentation/Add-PnPFileToSiteTemplate.md
- src/Commands/Provisioning/Site/InvokeSiteTemplate.cs
- src/Commands/Provisioning/Tenant/InvokeTenantTemplate.cs
N/A
Cleaned up some code and added clearer documentation on `Add-PnPFileToSiteTemplate`
> Updating documentation on `Add-PnPFileToSiteTemplate`

- CHANGELOG.md
- src/Commands/Site/SetSite.cs
Fixes #1343 
Fix for Set-PnPSite not working with DisableCompanyWideSharingLinks parameter
> Fix #1343 - issue with Set-PnPSite not working with DisableCompanyWideSharingLinks parameter

- documentation/Set-PnPListItemPermission.md
All examples were based on a specific user, so a group one is nice to have
None, adding documentation example
A change in the documentation for Set-PnPListItemPermission
> Adding example when using the -group parameter

- CHANGELOG.md
- src/Commands/Lists/GetListPermissions.cs
Fixes #715 
Fix issue with PnP list permissions displaying wrong data
> Fix #715 - issue with list permissions

- documentation/Get-PnPSiteTemplate.md
Updated Get-PnPSiteTemplate documentation to put handlers in alphabetical order and add Syntex handler and example.
> Updated Get-PnPSiteTemplate documentation - Syntex

- src/Commands/Resources/SharePointPermissions.json
NA
Updated the permissions json to include SharePoint Selected sites permission
> Feature add support for SP sites.selected permissions

- CHANGELOG.md
- src/Commands/Admin/SetTenantSite.cs
Fixes #1525 
Fix issue with PnPTenantSite not working correctly for some properties
> Fix #1525 - issue with Set-PnPTenantSite parameters

- documentation/Add-PnPTaxonomyField.md
Noticed TaxonomyItemID was listed as optional in ID syntax so corrected. Also added example 2 with TaxonomyItemID example.
> Update Add-PnPTaxonomyField.md to fix TaxonomyItemID and add example

- CHANGELOG.md
- src/Commands/Provisioning/Site/AddDataRowsToSiteTemplate.cs
Fixes #1387 
Added a warning about User not found during list data extraction, will return null.
> Fix #1387 - issue with user data extraction

- CHANGELOG.md
- src/Commands/RecycleBin/GetRecycleBinItem.cs
Fixes #1530 
Fixed issue with retrieving 2nd stage list items from recycle bin.
No good way to fix this because CSOM method doesn't have better way, so will retrieve list items and then splice them
> Fix #1530 - issue with recycle bin item retrieval

- CHANGELOG.md
- src/Commands/Pages/AddPageSection.cs
- src/Commands/Pages/AddPageTextPart.cs
- src/Commands/Pages/AddPageWebPart.cs
N/A
Removing obsolete aliases from cmdlets which were supposed to be removed in version 1.5.0 already
> Removing obsolete aliases from cmdlets

- documentation/Get-PnPWebPart.md
> Get-PNPWebpart only works with classic pages

- pages/templates/material/partials/scripts.tmpl.partial
Added Clarity to documentation
> Added Clarity code

- pages/templates/material/partials/scripts.tmpl.partial
> Revert "Added Clarity code"

- CHANGELOG.md
- pages/templates/material/partials/scripts.tmpl.partial
Added clarity analytics for docs pages
NA
Added clarity analytics for PnP documentation
> Feature - clarity analytics

- CHANGELOG.md
- documentation/Get-PnPListDesign.md
- src/Commands/ListDesign/GetListDesign.cs
-  New Feature
New cmdlet Get-PnPListDesign to retrieve List Designs that have been registered on the current tenant. When providing a name with -Identity, it returns all list designs with that name.
> New cmdlet Get-PnPListDesign

- documentation/Set-PnPAzureADAppSitePermission.md
Noticed the Permission parameters did not match what's in the code behind the parameter. This page was missing "Manage" and "FullControl" permissions so I have added them
Thanks
Leon
> Updated permission parameters on Set-PnPAzureADAppSitePermission

- src/ALC/ApplicationInsights.cs
- src/ALC/TelemetryClient.cs
- [x ] Bug Fix
Fixes #1247, 
Implementing a singleton pattern on TelemetryClient to avoid memory leak with repeating connect-pnponline calls
> telemetry as singleton pattern

- documentation/Set-PnPTenant.md
N/A
Clarifying documentation around `-DisabledWebPartIds` to list exactly which webparts are currently able to be disabled along with their respective Ids
> Updated documentation on `Set-PnPTenant -DisabledWebPartIds`

- CHANGELOG.md
- src/Commands/ContentTypes/Get-PnPContentTypePublishingStatus.cs
- src/Commands/ContentTypes/Publish-PnPContentType.cs
- src/Commands/ContentTypes/Unpublish-PnPContentType.cs
NA
Improved the cmdlets by removing unnecessary `ExecuteQuery`
Replaced `ExecuteQuery` with `ExecuteQueryRetry`
> Feature : Improved PnP ContentType publishing commands

- CHANGELOG.md
- src/Commands/Utilities/TeamsUtility.cs
Fixes #1585 
Issue adding owner to teams
> Fix #1585 - issue with adding owners and users

- CHANGELOG.md
- documentation/Rename-PnPTenantSite.md
- src/Commands/Admin/RenameTenantSite.cs
- src/Commands/Model/SPOSiteRename.cs
Fixes #603 
Added cmdlet to change the URL of a SPO site collection
> Feature #603 - added cmdlet to rename site URL

- documentation/Add-PnPApplicationCustomizer.md
N/A
Added clarification when to use the `Add-PnPApplicationCustomizer` cmdlet
> Added clarification when to use the `Add-PnPApplicationCustomizer` cmdlet

- documentation/Sync-PnPSharePointUserProfilesFromAzureActiveDirectory.md
- src/Commands/Utilities/SharePointUserProfileSync.cs
Relates to https://github.com/pnp/powershell/issues/1495
Updated documentation to clarify usage of -Folder on Sync-PnPSharePointUserProfilesFromAzureActiveDirectory
> Updated documentation to clarify usage of `-Folder` on `Sync-PnPSharePointUserProfilesFromAzureActiveDirectory`

- src/Commands/Utilities/FileUtilities.cs
- src/Commands/Utilities/ProvisioningHelper.cs
> Bugfix for PR#1638

- documentation/Set-PnPSiteGroup.md
No related issue
Typo within the example commandlet.
Changed | char to a "
> Char typo in Example 2

- documentation/Add-PnPEventReceiver.md
None
Suggested missing description
> Suggested missing description

- CHANGELOG.md
- documentation/Set-PnPTenant.md
- src/Commands/Admin/SetTenant.cs
Fixes #1668 
Added `Force`  parameter to `Set-PnPTenant` cmd to allow skipping confirmation question
> Feature #1668 - added force parameter to Set-PnPTenant

- documentation/Add-PnPSiteDesign.md
- documentation/Set-PnPSiteDesign.md
N/A
Clarifies a few things around using `Add-PnPSiteDesign` and `Set-PnPSiteDesign`
> Documentation updates to the `Add/Set-PnPSiteDesign` cmdlets

- documentation/Rename-PnPTenantSite.md
> Corrected wording on help page

- documentation/Get-PnPAzureADAppSitePermission.md
Fixed wording of documentation and added missing example descriptive text.
> Update Get-PnPAzureADAppSitePermission.md Documentation

- CHANGELOG.md
- documentation/Set-PnPSite.md
- documentation/Set-PnPTenantSite.md
- src/Commands/Admin/SetTenantSite.cs
- src/Commands/Site/SetSite.cs
NA
Added `MediaTranscription` to `Set-PnPTenantSite` and `Set-PnPSite` cmdlets
> Feature: added additional props to PnPTenantSite cmdlet

- CHANGELOG.md
- src/Commands/Admin/GetTenantSite.cs
Fixes #1717
Return Get-PnPTenantSite even if template name is specified in a different case.
> Fix #1717 - issue with Get-PnPTenantSite case sensitivity

- documentation/Set-PnPList.md
- documentation/Set-PnPListPermission.md
N/A
Added additional documentation around setting permissions on lists
> Added additional documentation around setting permissions on lists

- CHANGELOG.md
- src/Commands/DocumentSets/AddDocumentSet.cs
Fixes #1710 
Issue with Document Set Content Type ID
> #1710 - issue with Add-PnPDocumentSet

- CHANGELOG.md
- src/Commands/ContentTypes/AddContentTypesFromContentTypeHub.cs
Fixes #1809 
Fixes the usage of Site parameter
> Fix #1809 - issue with usage of Site parameter

- CHANGELOG.md
- src/Commands/Files/GetFile.cs
Fixes #1618 
Issue with downloading files in PS 5
> Fix #1618 - issue with Get-PnPFile in PS 5 hanging

- src/Commands/Model/Teams/Team.cs
- src/Commands/Model/Teams/TeamFunSettings.cs
Fixes #1824
Extra properties when retrieving a team.
> [Enhancement] Extra properties when retrieving team

- src/Commands/Model/PropertyBagValue.cs
- src/Commands/Web/AddIndexedProperty.cs
- src/Commands/Web/GetAvailableLanguage.cs
- src/Commands/Web/GetIndexedPropertyKeys.cs
- src/Commands/Web/GetPropertyBag.cs
- src/Commands/Web/GetRequestAccessEmails.cs
- src/Commands/Web/GetSubweb.cs
- src/Commands/Web/GetWeb.cs
- src/Commands/Web/GetWebHeader.cs
- src/Commands/Web/InvokeWebAction.cs
- src/Commands/Web/NewWeb.cs
- src/Commands/Web/RemovePropertyBagValue.cs
- src/Commands/Web/RemoveWeb.cs
- src/Commands/Web/RemovedIndexedProperty.cs
- src/Commands/Web/RequestReIndexWeb.cs
- src/Commands/Web/SetIndexedProperties.cs
- src/Commands/Web/SetPropertyBagValue.cs
- src/Commands/Web/SetRequestAccessEmails.cs
- src/Commands/Web/SetWeb.cs
- src/Commands/Web/SetWebHeader.cs
- src/Commands/Web/SetWebPermission.cs
- src/Commands/WebParts/AddWebPartToWebPartPage.cs
- src/Commands/WebParts/AddWebPartToWikiPage.cs
- src/Commands/WebParts/GetWebPart.cs
- src/Commands/WebParts/GetWebPartProperty.cs
- src/Commands/WebParts/GetWebPartXml.cs
- src/Commands/WebParts/RemoveWebPart.cs
- src/Commands/WebParts/SetWebPartProperty.cs
Adds OutputType Attribute to the next 27 cmdlets, for better command completion:
* Web
* WebPart
> Add OutputType Attribute - #4 (Web and WebPart)

- documentation/Get-PnPFlowRun.md
No issue created for this.
Fixes -Flow parameter description.
> Update Get-PnPFlowRun documentation

- documentation/Add-PnPFile.md
N/A
Adding missing documentation on using `-Content` with `Add-PnPFile`
> Adding missing documentation on using `-Content` with `Add-PnPFile`

- src/Commands/Properties/launchSettings.json
- src/Commands/_debug/debug.ps1
mentioned in #1823
- launchsettings to debug PnP.PowerShell Module in Visual Studio
> debugging in visual studio

- CHANGELOG.md
- src/Commands/PnP.PowerShell.csproj
- src/Commands/WindowsSdk.targets
NA
Bumping .NET Framework version to 4.6.2 as  4.6.1 is out of support
> Feature: bumping .NET Framework version to 4.6.2

- src/Commands/Utilities/ListItemHelper.cs
Fixes #1595 
Issue with tax item update
> Fix #1595 - issue with tax item update

- src/Commands/Base/AddStoredCredential.cs
- src/Commands/Base/DisconnectOnline.cs
- src/Commands/Base/GetAccessToken.cs
- src/Commands/Base/GetAppAuthAccessToken.cs
- src/Commands/Base/GetAuthenticationRealm.cs
- src/Commands/Base/GetChangeLog.cs
- src/Commands/Base/GetConnection.cs
- src/Commands/Base/GetContext.cs
- src/Commands/Base/GetDiagnostics.cs
- src/Commands/Base/GetException.cs
- src/Commands/Base/GetPowerShellTelemetryEnabled.cs
- src/Commands/Base/GetProperty.cs
- src/Commands/Base/GetStoredCredential.cs
- src/Commands/Base/InvokeBatch.cs
- src/Commands/Base/InvokeQuery.cs
- src/Commands/Base/InvokeSPRestMethod.cs
- src/Commands/Base/NewBatch.cs
- src/Commands/Base/PnPSharePointCmdlet.cs
- src/Commands/Base/RemoveStoredCredential.cs
- src/Commands/Model/Diagnostics.cs
Adds OutputType Attribute to the next 19 cmdlets, for better command completion
> Add OutputType Attribute - wave 5 (Base)

- src/Commands/Model/SubscribeSharePointNewsDigestStatus.cs
- src/Commands/RecycleBin/ClearRecycleBinItem.cs
- src/Commands/RecycleBin/ClearTenantRecycleBinItem.cs
- src/Commands/RecycleBin/GetRecycleBinItem.cs
- src/Commands/RecycleBin/GetTenantRecycleBinItem.cs
- src/Commands/RecycleBin/MoveRecycleBinItem.cs
- src/Commands/RecycleBin/RestoreRecycleBinItem.cs
- src/Commands/RecycleBin/RestoreTenantRecycleBinItem.cs
- src/Commands/Transformation/InvokeTransformation.cs
- src/Commands/UserProfiles/ExportUserProfile.cs
- src/Commands/UserProfiles/GetSubscribeSharePointNewsDigest.cs
- src/Commands/UserProfiles/GetUPABulkImportStatus.cs
- src/Commands/UserProfiles/GetUserOneDriveQuota.cs
- src/Commands/UserProfiles/GetUserProfileProperty.cs
- src/Commands/UserProfiles/NewPersonalSite.cs
- src/Commands/UserProfiles/NewUPABulkImportJob.cs
- src/Commands/UserProfiles/RemoveUserProfile.cs
- src/Commands/UserProfiles/ResetUserOneDriveQuotaToDefault.cs
- src/Commands/UserProfiles/SetSubscribeSharePointNewsDigest.cs
- src/Commands/UserProfiles/SetUserOneDriveQuota.cs
- src/Commands/UserProfiles/SetUserProfileProperty.cs
- src/Commands/UserProfiles/SyncSharePointUserProfilesFromAzureActiveDirectory.cs
- src/Commands/Viva/AddVivaConnectionsDashboardACE.cs
- src/Commands/Viva/GetVivaConnectionsDashboard.cs
- src/Commands/Viva/RemoveVivaConnectionsACE.cs
- src/Commands/Viva/UpdateVivaConnectionsACE.cs
Adds OutputType Attribute to the next 26 cmdlets, for better command completion:
* Viva
* UserProfile
* RecycleBin
* Transformation
> Add OutputType Attribute - wave 6 (Viva, UserProfile, RecycleBin, Transformation)

- docker/hub.docker.md
Fixes issue in the feature #1580
In the documentation, docker hub organization was wrong. Corrected in this PR.
> corrected organization name in docker hub md

- documentation/Get-PnPPlannerConfiguration.md
Haven't created an issue for this.
Small docs typo fix.
> Fixes documentation typo for `Get-PnPPlannerConfiguration`

- pages/articles/batching.md
None
Fix links in batching article.
> Fix links in batching.md

- pages/articles/azurefunctions.md
NA
Fixed article to use the newer Az module instead of the deprecated AzureAD modules
> Fix: Article update for Azure functions

- src/Commands/Model/AzureAD/UserDelta.cs
- src/Commands/Utilities/AzureAdUtility.cs
N/A
Removed the NextLink from the model as it wasn't used anyway and caused confusion
> Removed the NextLink from the Users delta model

- src/Commands/Base/PnPSharePointCmdlet.cs
- src/Commands/Utilities/TeamsUtility.cs
NA
Remove hardcoded references to MS Graph endpoints where possible.
> Fix: remove hardcoded references for MSGraph to handle other clouds

- CHANGELOG.md
- src/Commands/Model/Planner/PlannerTask.cs
Fixes #1956
Fixed type of `CompletedBy` property in `PlannerTask` model.
> Fixes JSON parse issue for `CompletedBy` property in `PlannerTask` model

- src/Commands/Teams/GetTeamsChannel.cs
Fixes #1872 
Fix for teams channel enumeration
> Fix #1872 - issue with teams channel enumeration

- src/Commands/Site/UpdateSiteClassification.cs
Fixes #1971 
Fix site classification settings issue, where the parameter was ignored.
> Fix #1971 - issue with site classification parameter ignored

- documentation/Add-PnPFieldToContentType.md
- src/Commands/ContentTypes/AddFieldToContentType.cs
Fixes #1092
Added additional parameter if you want to skip the pushing of fields to child content types.
> Fix #1092 - issue with orphaned CTs

- src/Commands/Files/GetFileVersion.cs
Fixes #1023
Allow piping and correctly enumerating the file version collections
> Fix #1023 - issue with Get-PnPFileVersion filtering

- src/Commands/Admin/GetSiteCollectionAppCatalogs.cs
- src/Commands/ContentTypes/AddContentTypesFromContentTypeHub.cs
- src/Commands/Files/FindFile.cs
- src/Commands/Lists/GetListPermissions.cs
- src/Commands/Search/GetSearchConfiguration.cs
- src/Commands/Search/GetSearchCrawlLog.cs
- src/Commands/Web/GetIndexedPropertyKeys.cs
- src/Commands/Webhooks/GetWebhookSubscriptions.cs
> Feature: added better piping support for certain cmdlets

- src/Commands/UserProfiles/NewUPABulkImportJob.cs
N/A
Several optimizations to New-PnPUPABulkImportJob
> Optimizations to `New-PnPUPABulkImportJob`

- documentation/Get-PnPAccessToken.md
- src/Commands/Base/GetAccessToken.cs
N/A
Fixing messed up paramsets in `Get-PnPAccessToken`
Changelog entry not needed as the bug was introduced after the 1.10 release
> Fixing messed up paramsets in `Get-PnPAccessToken`

- documentation/Set-PnPTenant.md
N/A
Descriptions for parameters
> Set-PnPTenant parameter description

- documentation/Add-PnPListItem.md
- documentation/Publish-PnPSyntexModel.md
- documentation/Remove-PnPListItem.md
- documentation/Request-PnPSyntexClassifyAndExtract.md
- documentation/Set-PnPListItem.md
- documentation/Unpublish-PnPSyntexModel.md
N/A
Added hyperlink, for the batching reference article, to the **Supports batching** image on all supporting cmdlets.
> Add hyperlink to batching reference article to help docs

- documentation/Add-PnPListItem.md
- documentation/Publish-PnPSyntexModel.md
- documentation/Remove-PnPListItem.md
- documentation/Request-PnPSyntexClassifyAndExtract.md
- documentation/Set-PnPListItem.md
- documentation/Unpublish-PnPSyntexModel.md
Batch image not loading
Fixes to documentation to reflect path of blob image so it now displays
> Batch image path update on Batch Documentation

- CHANGELOG.md
- pages/articles/authentication.md
> Small typo fix

- documentation/Invoke-PnPSiteSwap.md
- documentation/Remove-PnPTenantDeletedSite.md
- documentation/Request-PnPPersonalSite.md
- documentation/Restore-PnPTenantSite.md
- src/Commands/Admin/InvokeSiteSwap.cs
- src/Commands/Admin/RestoreTenantSite.cs
- src/Commands/Base/PnPSharePointCmdlet.cs
N/A
Adding verbose logging to SpoOperation wait supporting cmdlets
> Adding verbose logging to SpoOperation wait supporting cmdlets

- documentation/Set-PnPTenant.md
- src/Commands/Admin/SetTenant.cs
- src/Commands/Model/SPOTenant.cs
Fixes #2189 
Adding IsLoopEnabled parameters to Get\Set-PnPTenant cmdlets
> #2189 - added IsLoopEnabled parametes for tenant cmdlets

- src/Commands/Lists/CopyList.cs
Fixes #2309 
Issue with copying lists to destination site collection
> Fix #2309 - issue with Copy-PnPList to destination web

- src/Commands/Site/AddAvailableSiteClassification.cs
- src/Commands/Site/AddRoleDefinition.cs
- src/Commands/Site/AddSiteCollectionAdmin.cs
- src/Commands/Site/AddTeamsTeam.cs
- src/Commands/Site/DisableSharingForNonOwnersOfSite.cs
- src/Commands/Site/DisableSiteClassification.cs
- src/Commands/Site/EnableCommSite.cs
- src/Commands/Site/EnableSiteClassification.cs
- src/Commands/Site/GetAuditing.cs
- src/Commands/Site/GetAvailableSiteClassification.cs
- src/Commands/Site/GetRoleDefinition.cs
- src/Commands/Site/GetSharingForNonOwnersOfSite.cs
- src/Commands/Site/GetSite.cs
- src/Commands/Site/GetSiteCollectionAdmin.cs
- src/Commands/Site/RemoveRoleDefinition.cs
- src/Commands/Site/RemoveSiteCollectionAdmin.cs
- src/Commands/Site/SetAppSideLoading.cs
- src/Commands/Site/SetAuditing.cs
- src/Commands/Site/SetRoleDefinition.cs
- src/Commands/Site/SetSite.cs
- src/Commands/Site/SetTeamifyPromptHidden.cs
- src/Commands/Site/TestMicrosoft365GroupAliasIsUsed.cs
- src/Commands/Site/UpdateAvailableSiteClassification.cs
Adds OutputType Attribute to the next 23 cmdlets, for better command completion.
Follow up to https://github.com/pnp/powershell/pull/1763#issuecomment-1099695169
> Add OutputType Attribute - wave 7 (Site)

- docker/hub.docker.md
NA
Updated docker hub page description
> Updated docker hub page description

- CHANGELOG.md
- documentation/Add-PnPAlert.md
- src/Commands/Principals/AddAlert.cs
Fixes #2355 
added AlertTemplateName param to Add-PnPAlert
> Feature #2355 - added AlertTemplateName param to Add-PnPAlert

- src/Commands/Admin/GetTenantSite.cs
- src/Commands/Lists/CopyList.cs
NA
Added missing retry for Set-PnPTenantSite and Copy-PnPList
> Added missing retry for Set-PnPTenantSite and Copy-PnPList

- CHANGELOG.md
- src/Commands/Admin/SetTenant.cs
Fixes #2366 
Fix issue with `-Force ` parameter not being recognized.
> Fix #2366 - issue with Set-PnPTenant force not working

- build/Build-Nightly.ps1
- build/Generate-PredictorCommands.ps1
As discussed with @gautamdsheth and @KoenZomers updated `Build-Nightly` with code to generate commands that will be used by the predictor module.
> feat: added predictor code

- build/Build-Nightly.ps1
- build/Generate-PredictorCommands.ps1
Updated file reference so that nightly build works correctly.
> fix(predictor): updated file reference

- CHANGELOG.md
- documentation/Add-PnPPageImageWebPart.md
- src/Commands/Pages/AddPageImageWebPart.cs
NA
Adds cmdlet to add image to page easily using this new cmdlet.
> Feature: Adds the ability to add image webpart to a page

- CHANGELOG.md
- src/Commands/ContentTypes/RemoveFieldFromContentType.cs
NA
Improve null check for non-existing fields
> Feature: improve null check for non-existing fields

- documentation/Get-PnPSyntexModel.md
- documentation/Get-PnPSyntexModelPublication.md
- documentation/Publish-PnPSyntexModel.md
- documentation/Request-PnPSyntexClassifyAndExtract.md
Changed documentation pages to reflect SharePoint Syntex being renamed to Microsoft Syntex
> Microsoft Syntex doc updates

- CHANGELOG.md
- documentation/Set-PnPSite.md
- documentation/Set-PnPTenant.md
- src/Commands/Admin/SetTenant.cs
- src/Commands/Model/SPOTenant.cs
- src/Commands/Site/SetSite.cs
NA
Enable restrict site access capabilities on the Tenant and SharePoint site collections
> Feature: Ability to set Restricted Access control on tenant and sites

- CHANGELOG.md
- documentation/Get-PnPDeletedTeam.md
- src/Commands/Model/Teams/DeletedTeam.cs
- src/Commands/Teams/GetDeletedTeamsTeam.cs
- src/Commands/Utilities/TeamsUtility.cs
NA
Added feature to retrieve deleted teams team.
> Feature: added cmdlet to retrieve deleted teams

- src/Commands/Admin/GetTenantId.cs
N/A
Voids having to type `Get-PnPTenandId -TenantUrl contoso.sharepoint.com`. Now this will suffice as well `Get-PnPTenantId contoso.sharepoint.com`.
> Added value from pipeline to `Get-PnPTenantId`

- CHANGELOG.md
- documentation/Set-PnPBuiltInSiteTemplateSettings.md
- src/Commands/Enums/BuiltInSiteTemplates.cs
- src/Commands/Model/SharePoint/BuiltInSiteTemplateSettings.cs
N/A
Added latest added SharePoint Online Site Templates to `Set-PnPBuiltInSiteTemplateSettings` allowing them to be hidden or shown
> Added latest added SharePoint Online Site Templates to `Set-PnPBuiltInSiteTemplateSettings`

- CHANGELOG.md
- documentation/Set-PnPTenant.md
- src/Commands/Admin/SetTenant.cs
Requested through issue #2628 
Added EnableAzureADB2BIntegration and SyncAadB2BManagementPolicy parameters to Set-PnPTenant
> Added `EnableAzureADB2BIntegration` and `SyncAadB2BManagementPolicy` to `Set-PnPTenant`

- src/Commands/Pages/AddPage.cs
Fixes #2572 
Swallow PnP Core exception of it tries to activate multilingual feature multiple times
> Fix #2572 - issue with feature activation in same session for page translation

- documentation/Copy-PnPItemProxy.md
Fixes #2584 
Added docs for the cmdlet
> #2584 - Added Docs for Copy-PnPItemProxy cmdlet

- CHANGELOG.md
- src/Commands/Principals/ExportUserInfo.cs
- src/Commands/Principals/RemoveUserInfo.cs
NA
Fixed issue with `Export-PnPUserInfo` and `Remove-PnPUserInfo` cmdlets not working.
> Fix: issue with userinfo cmdlets not working

- CHANGELOG.md
- documentation/Get-PnPMicrosoft365Group.md
- src/Commands/Microsoft365Groups/GetMicrosoft365Group.cs
- src/Commands/Utilities/Microsoft365GroupsUtility.cs
NA
Added filter parameter to `Get-PnPMicrosoft365Group` cmdlet to support server side filtering with advanced capabilities
> Feature: added filter parameter to Get-PnPMicrosoft365Group cmdlet

- CHANGELOG.md
- src/Commands/ContentTypes/SetContentType.cs
Fixes #2751 
Changed param assignments to allow for every param to be used
> Fixed `Set-PnPContentType` not allowing simple changes

- src/Commands/Lists/AddListItem.cs
- src/Commands/Lists/SetListItem.cs
Closes #2799
#2799
Fixes retentionlabel issue for UnlockedAsDefault labels.
> Fix retentionlabel issue for UnlockedAsDefault labels. Closes #2799

- CHANGELOG.md
- documentation/Send-PnPMail.md
Typo with the word "SharePoint" in the Send-PnPMail command
> Typo in the word "SharePoint"

- pages/articles/installation.md
add " -Scope CurrentUser" to increase install success rate by not requiring administrative rights
> installation.md: add " -Scope CurrentUser"

- documentation/Set-PnPPage.md
Fixes #2870 
Correct Accepted values for the HeaderLayoutType parameter for the Set-PnPPage cmdlet documentation
> Add HeaderLayoutType accepted values in Set-PnPPage.md

- CHANGELOG.md
- src/Commands/AzureAD/RegisterAzureADApp.cs
Fixes #2872 
Issue with cert path if existing certificate is provided.
> Fix #2872 - issue with certificate path if exisiting cert is provided

- documentation/Clear-PnPListItemAsRecord.md
- documentation/Connect-PnPOnline.md
- documentation/Copy-PnPTeamsTeam.md
- documentation/Disable-PnPFlow.md
- documentation/Enable-PnPFlow.md
- documentation/Enable-PnPSiteClassification.md
- documentation/Export-PnPPageMapping.md
- documentation/Get-PnPApplicationCustomizer.md
- documentation/Get-PnPAvailableSensitivityLabel.md
- documentation/Get-PnPAzureADGroup.md
- documentation/Get-PnPAzureADServicePrincipalAssignedAppRole.md
- documentation/Get-PnPFlow.md
- documentation/Get-PnPHubSiteChild.md
- documentation/Get-PnPPlannerRosterPlan.md
- documentation/Get-PnPPlannerTask.md
- documentation/Get-PnPSiteSensitivityLabel.md
- documentation/Get-PnPSiteTemplate.md
- documentation/Get-PnPSubWeb.md
- documentation/Get-PnPTenantId.md
- documentation/Get-PnPTermLabel.md
- documentation/Get-PnPTermSet.md
- documentation/Get-PnPUser.md
- documentation/Get-PnPWebTemplates.md
- documentation/Invoke-PnPBatch.md
- documentation/Invoke-PnPSiteSwap.md
- documentation/Invoke-PnPSiteTemplate.md
- documentation/Invoke-PnPTenantTemplate.md
- documentation/Measure-PnPWeb.md
- documentation/Move-PnPFolder.md
Text typo fixes in read me files
> Fixing typos in readme files

- src/PnP.PowerShell.sln
- src/Tests/Lists/SetPnPViewTests.cs
- src/Tests/OriginalTests/BaseTests.cs
- src/Tests/OriginalTests/BrandingTests.cs
- src/Tests/OriginalTests/ClientSidePagesTests.cs
- src/Tests/OriginalTests/DiagnosticTests.cs
- src/Tests/OriginalTests/FeatureTests.cs
- src/Tests/OriginalTests/FieldsTests.cs
- src/Tests/OriginalTests/FilesTest.cs
- src/Tests/OriginalTests/ListDataRowProvisioningTemplate.cs
- src/Tests/OriginalTests/WebPartsTests.cs
- src/Tests/OriginalTests/WebhookSubscriptionsTests.cs
- src/Tests/PnP.PowerShell.Tests.csproj
- src/Tests/TestCommon.cs
NA
Fixed the test project.
Not sure if anybody is going to use it or something.
> Fix the test project

- documentation/Connect-PnPOnline.md
- pages/articles/azureautomationrunbook.md
- pages/articles/azurefunctions.md
- src/Commands/Base/ConnectOnline.cs
- src/Commands/Base/PnPConnection.cs
N/A
Making URL optional when using a managed identity
> Making URL optional when using a managed identity

- src/Commands/PnP.PowerShell.csproj
> Changed copyright

- .github/workflows/buildpr.yml
- .github/workflows/checkdocumentationbuild.yml
- .github/workflows/cleanupnightlyreleases.yml
- .github/workflows/nightlyrelease.yml
- .github/workflows/release.yml
NA
Improve pipelines to use newer features
> Feature: improve pipelines

- .github/workflows/builddocsite.yml
- .github/workflows/buildexternalhelp.yml
- .github/workflows/checkdocumentationbuild.yml
- .github/workflows/nightlyrelease.yml
NA
Bump docfx version and other improvements to pipelines
> Feature: bump docfx version

- .github/workflows/builddocsite.yml
- .github/workflows/checkdocumentationbuild.yml
> Feature: improve pipeline for docs

- pages/cmdlets/index.md
> Adding cmdlet index page

- pages/articles/vscodeextension.md
I updated the VS Code extensions description a bit.
> Update VS Code extension description

- documentation/Set-PnPTenant.md
- src/Commands/Admin/SetTenant.cs
- src/Commands/Model/SPOTenant.cs
N/A
Fixing broken build by removing DisableListSync and SyncAadB2BManagementPolicy which have been removed from CSOM
> Fixing broken build by removing DisableListSync and SyncAadB2BManagementPolicy

- .vscode/tasks.json
- CHANGELOG.md
- documentation/Set-PnPPage.md
- src/Commands/Pages/SetPage.cs
Fixes #3416 
This PR contains a parameter which would all Modern Page to display Published date in page title
> #3416 - Show Published Date in Page title

- CHANGELOG.md
- src/Commands/Files/AddFile.cs
Fixes #3112
Automatically checkout file if checkin type is specified.
> Fix #3112 - issue with file checkout and checkin

- src/Commands/JsonConverters/MicrosoftSearchExternalItemPropertyConverter.cs
- src/Commands/Model/Graph/MicrosoftSearch/ExternalItem.cs
- src/Commands/Search/SetSearchExternalItem.cs
N/A
Fixing two issues with `Set-PnPSearchExternalItem` being the properties not being provided in the returned output and when using `-GrantEveryone` it throwing an exception.
> Fixing two issues with `Set-PnPSearchExternalItem`

- src/Commands/Pages/AddPage.cs
- src/Commands/Pages/AddPageImageWebPart.cs
- src/Commands/Pages/AddPageSection.cs
- src/Commands/Pages/AddPageTextPart.cs
- src/Commands/Pages/AddPageWebPart.cs
- src/Commands/Pages/GetPage.cs
- src/Commands/Pages/MovePageComponent.cs
- src/Commands/Pages/RemovePageComponent.cs
- src/Commands/Pages/SetPage.cs
- src/Commands/Pages/SetPageTextPart.cs
- src/Commands/Pages/SetPageWebPart.cs
NA
Added output types to page cmdlets
> Feature: added output types to page cmdlets

- src/Commands/Principals/AddGroupMember.cs
- src/Commands/Principals/ExportUserInfo.cs
- src/Commands/Principals/RemoveAlert.cs
- src/Commands/Principals/RemoveGroup.cs
- src/Commands/Principals/RemoveGroupMember.cs
- src/Commands/Principals/RemoveSiteGroup.cs
- src/Commands/Principals/RemoveUser.cs
- src/Commands/Principals/RemoveUserInfo.cs
- src/Commands/Principals/SetGroup.cs
- src/Commands/Principals/SetGroupPermissions.cs
- src/Commands/Principals/UpdateUserType.cs
NA
Added output types for Principals cmdlets
> Feature: added output types for Principals cmdlets

- src/Commands/SiteDesigns/AddSiteDesign.cs
- src/Commands/SiteDesigns/AddSiteDesignFromWeb.cs
- src/Commands/SiteDesigns/AddSiteDesignTask.cs
- src/Commands/SiteDesigns/AddSiteScriptPackage.cs
- src/Commands/SiteDesigns/GetSiteDesignRights.cs
- src/Commands/SiteDesigns/GetSiteDesignRun.cs
- src/Commands/SiteDesigns/GetSiteDesignRunStatus.cs
- src/Commands/SiteDesigns/GetSiteScriptFromWeb.cs
- src/Commands/SiteDesigns/GrantSiteDesignRights.cs
- src/Commands/SiteDesigns/InvokeSiteDesign.cs
- src/Commands/SiteDesigns/InvokeSiteScript.cs
- src/Commands/SiteDesigns/RemoveSiteDesign.cs
- src/Commands/SiteDesigns/RemoveSiteDesignTask.cs
- src/Commands/SiteDesigns/RemoveSiteScript.cs
- src/Commands/SiteDesigns/RevokeSiteDesignRights.cs
- src/Commands/SiteDesigns/SetBuiltInSiteTemplateSettings.cs
- src/Commands/SiteDesigns/SetSiteDesign.cs
- src/Commands/SiteDesigns/SetSiteScript.cs
- src/Commands/SiteDesigns/SetSiteScriptPackage.cs
- src/Commands/SiteDesigns/UpdateSiteDesignFromWeb.cs
NA
Added output types for site scripts and site designs.
> Feature: added output types for site scripts and designs

- src/Commands/Base/PnPAdminCmdlet.cs
N/A
Clarified the error message when running a PnPAdminCmdlet so it also includes a hint towards checking for PIM activation as many customers are using that nowadays and forget to enable it
> Clarified the error message when running a PnPAdminCmdlet

- src/Commands/Apps/AddAzureADServicePrincipalAppRole.cs
- src/Commands/Apps/GetAzureADAppSitePermission.cs
- src/Commands/Apps/GetAzureADServicePrincipal.cs
- src/Commands/Apps/GetAzureADServicePrincipalAssignedAppRole.cs
- src/Commands/Apps/GetAzureADServicePrincipalAvailableAppRole.cs
- src/Commands/Apps/GrantAzureADAppSitePermission.cs
- src/Commands/Apps/RemoveAzureADServicePrincipalAssignedAppRole.cs
- src/Commands/Apps/RevokeAzureADAppSitePermission.cs
- src/Commands/Apps/SetAzureADAppSitePermission.cs
- src/Commands/AzureAD/AddAzureADGroupMember.cs
- src/Commands/AzureAD/AddAzureADGroupOwner.cs
- src/Commands/AzureAD/ClearAzureADGroupMember.cs
- src/Commands/AzureAD/ClearAzureADGroupOwner.cs
- src/Commands/AzureAD/GetAzureADActivityReportDirectoryAudit.cs
- src/Commands/AzureAD/GetAzureADActivityReportSignIn.cs
- src/Commands/AzureAD/GetAzureADApp.cs
- src/Commands/AzureAD/GetAzureADAppPermission.cs
- src/Commands/AzureAD/GetAzureADGroup.cs
- src/Commands/AzureAD/GetAzureADGroupMember.cs
- src/Commands/AzureAD/GetAzureADGroupOwner.cs
- src/Commands/AzureAD/GetAzureADUser.cs
- src/Commands/AzureAD/NewAzureADGroup.cs
- src/Commands/AzureAD/NewAzureADUserTemporaryAccessPass.cs
- src/Commands/AzureAD/RegisterAzureADApp.cs
- src/Commands/AzureAD/RemoveAzureADApp.cs
- src/Commands/AzureAD/RemoveAzureADGroup.cs
- src/Commands/AzureAD/RemoveAzureADGroupMember.cs
- src/Commands/AzureAD/RemoveAzureADGroupOwner.cs
- src/Commands/AzureAD/SetAzureADGroup.cs
Related to https://github.com/pnp/powershell/pull/3432
Added alias to the Azure AD cmdlets
NA
> Add alias to Azure AD cmdlets

- documentation/Get-PnPContainer.md
- src/Commands/Admin/GetContainer.cs
- src/Commands/Base/PipeBinds/ContainerPipeBind.cs
- src/Commands/Properties/Resources.Designer.cs
- src/Commands/Properties/Resources.resx
New cmdlet Get-PnPContainer to allows retrieval of information about SharePoint repository applications like loop or Microsoft Designer. It will help give visibility of workspaces/repositories within a tenant.
https://learn.microsoft.com/en-gb/powershell/module/sharepoint-online/get-spocontainer?view=sharepoint-ps
Files added 
- src\Commands\Admin\GetContainer.cs
- src\Commands\Base\PipeBinds\ContainerPipeBind.cs
- documentation\Get-PnPContainer.md
Modified files
- src\Commands\Properties\Resources.Designer.cs
- src\Commands\Properties\Resources.resx
> New cmdlet get-pnpcontainer

- MIGRATE-2.0-to-3.0.md
- documentation/Get-PnPPowerPlatformCustomConnector.md
- src/Commands/PowerPlatform/Environment/GetPowerPlatformCustomConnector.cs
N/A
Renaming `Get-PnPPowerPlatformConnector` to `Get-PnPPowerPlatformCustomConnector`
> Renaming `Get-PnPPowerPlatformConnector` to `Get-PnPPowerPlatformCustomConnector`

- src/Commands/Model/PowerPlatform/Environment/PowerPlatformSolution.cs
- src/Commands/Model/PowerPlatform/Environment/PowerPlatformSolutionPublisher.cs
- src/Commands/Teams/AddTeamsChannel.cs
> Fixed build warnings

- src/ALC/PnP.PowerShell.ALC.csproj
- src/Commands/Base/PnPPowerShellModuleInitializer.cs
- src/Commands/PnP.PowerShell.csproj
- src/Commands/Sdk.targets
- src/Commands/WindowsSdk.targets
- src/Commands/_debug/debug.ps1
> PnP PS v3 - first draft

- CHANGELOG.md
- src/Commands/Resources/GraphPermissions.json
Fixes #3835 to add additional perms
Added additional permissions to Graph application permissions set
> Fix #3835:  Added additional permissions to Graph

- documentation/Set-PnPTenantCdnPolicy.md
- documentation/Set-PnPTerm.md
- documentation/Set-PnPTermSet.md
- documentation/Set-PnPTheme.md
- documentation/Set-PnPUserOneDriveQuota.md
- documentation/Set-PnPUserProfileProperty.md
- documentation/Set-PnPView.md
- documentation/Set-PnPVivaConnectionsDashboardACE.md
- documentation/Set-PnPWebPartProperty.md
- documentation/Set-PnPWebPermission.md
- documentation/Set-PnPWebTheme.md
n/a
* Added Connection parameter description
* Fixed \<tenant> to show correctly
* Added description to Description and Parameter
* Reordered parameters alphabetically 
* Corrected spelling to align with support.microsoft.com
> Some documentation fixes

- src/Commands/PnP.PowerShell.csproj
NA
Bump MSAL.NET to latest version
> Feature: bump MSAL.NET to latest version

- .github/workflows/codeql.yml
> Create codeql.yml action to check code quality

- documentation/Get-PnPContainer.md
- documentation/Get-PnPContainerType.md
- documentation/Get-PnPContainerTypeConfiguration.md
- documentation/New-PnPContainerType.md
- documentation/Remove-PnPContainerType.md
- src/Commands/Admin/GetContainerType.cs
files for new cmdlet Get-PnPContainerType
- src\Commands\Admin\GetContainerType.cs
- documentation\Get-PnPContainerType.md
Minor documentation updates related to permissions required and typo fixes.
- documentation\Get-PnPContainer.md
- documentation\Get-PnPContainerTypeConfiguration.md
- documentation\New-PnPContainerType.md
- documentation\Remove-PnPContainerType.md
> New cmdlet Get-PnPContainerType and minor updates to docs.

- src/Commands/Model/SPOSite.cs
Fixes #3983
Adding additional props to tenant site cmdlet
> Update PnPTenantSite to include additional properties and their setters

- src/Commands/Admin/GetHomeSite.cs
- src/Commands/Model/SharePoint/CompanyPortalSiteDetails.cs
NA
Update Get-PnPHomeSite to include viva connections functionality
> chore: Update Get-PnPHomeSite to include Viva Connections functionality

- src/Commands/PnP.PowerShell.csproj
Security
Bump MSAL to latest for security fixes
> Security: Bump MSAL.NET to latest

- src/Commands/Model/SPOTenant.cs
Fixes #4028
Return additional property
> Feature #4028 : return EnableAIPIntegation in Get-PnPTenant cmdlet

- src/Commands/Base/ConnectOnline.cs
Fixes #3908
Improve connection validation , check only if validateConnection is specified
> Fix #3908: improve connection validation in ConnectOnline.cs

- src/Commands/Model/SPOSite.cs
Fixes #4041
Removed properties which were causing some issue fetching tenant site
> Fix #4041 : issue retrieving loop sharing information

- src/Commands/Utilities/REST/RestHelper.cs
N/A
Regression fix due to removal of async functionality
> Bugfix for async removal

- src/Commands/Admin/NewContainerType.cs
N/A
Following up on internal discussion
> Adding notice to source code of `New-SPOContainerType`

- src/Commands/Web/GetWebHeader.cs
Fixes #4132
Fixes null checking in group connected sites.
> Fix #4132 : issue with header background images in group connected sites

- documentation/Add-PnPListFoldersToSiteTemplate.md
- documentation/Get-PnPFolderItem.md
- documentation/Measure-PnPWeb.md
- src/Commands/Diagnostic/MeasurePnPWeb.cs
- src/Commands/Files/GetFolderItem.cs
- src/Commands/Provisioning/Site/AddListFoldersToSiteTemplate.cs
Fixes #4140
Added recurse alias for recursive to make it consistent with PowerShell standards
> Fix #4140 : added alias  recurse parameter for 3 cmdlets

- src/Commands/Base/PipeBinds/FilePipeBind.cs
Fixes #4105
Fixed issue with loading file sharing links
> Fix #4105 - issue with loading file sharing link when used with list item

- documentation/Add-PnPDocumentSet.md
- src/Commands/DocumentSets/AddDocumentSet.cs
> Fixed document set parent folder implementation

- src/Commands/Base/ConnectOnline.cs
Fixes #4131
Adds validate connection support for managed identity parameters
> Fix #4131 : support validate connection for managed identity

- documentation/Get-PnPApplicationCustomizer.md
- documentation/Get-PnPAvailableLanguage.md
- documentation/Get-PnPCustomAction.md
- documentation/Get-PnPDocumentSetTemplate.md
- documentation/Get-PnPEventReceiver.md
- documentation/Get-PnPFeature.md
- documentation/Get-PnPField.md
- documentation/Get-PnPFolder.md
- documentation/Get-PnPGroup.md
- documentation/Get-PnPRecycleBinItem.md
- documentation/Get-PnPSite.md
- documentation/Get-PnPSubWeb.md
- documentation/Get-PnPTerm.md
- documentation/Get-PnPTermGroup.md
- documentation/Get-PnPTermSet.md
- documentation/Get-PnPView.md
- documentation/Get-PnPWeb.md
- documentation/Measure-PnPList.md
- documentation/Resolve-PnPFolder.md
Fixes #4124
Updated docs to mention includes parameter
> Fix #4124 : update docs to mention includes parameter description

- src/Commands/Base/ConnectOnline.cs
- src/Commands/Planner/GetPlannerPlan.cs
- src/Commands/Planner/NewPlannerPlan.cs
- src/Commands/Planner/RemovePlannerPlan.cs
- src/Commands/Planner/SetPlannerPlan.cs
Fixes #3917
Updated code to use correct permissions for planner
> Fix #3917 : updated permissions for planner cmdlets

- src/Commands/Base/PnPSharePointCmdlet.cs
- src/Commands/Base/TokenHandler.cs
NA
Fix auth manager reuse issue with managed identity flow
> Fix: authentication manager issues with managed identity flow

- src/Commands/Base/ConnectOnline.cs
- src/Commands/Base/PnPGraphCmdlet.cs
- src/Commands/Base/TokenHandler.cs
NA
Fix minor issue with Get-PnPAccessToken cmdlets and other changes to managed identity to support custom azure env
> Fix issues with Get-PnPAccessToken cmdlet and others which have missing scope

- src/Commands/Base/PnPAzureManagementApiCmdlet.cs
Fixes #3852
Fix issue related to correct endpoint
> Fix #3852: fix issue related to correct resource usage for power platform cmdlets

- src/Commands/PnP.PowerShell.csproj
NA
Bump MSAL to latest to bring in the changes needed for WAM support
> Feature: Bump MSAL to latest versions

- documentation/Connect-PnPOnline.md
- src/Commands/Base/ConnectOnline.cs
- src/Commands/Base/PnPConnection.cs
Fixes #3971
Adds support for windows hello and other secure auth flows using WAM.
> Fix #3971 : add support for Windows hello and other auth methods

- build/Build-Nightly.ps1
NA
Fix issue with missing DLL for WAM implementation
> Fix build issue with WAM not working

- documentation/Connect-PnPOnline.md
- src/Commands/Base/ConnectOnline.cs
NA
Simplify login with Windows OS auth prompt
> Feature: simplify login with native OS prompt

- documentation/Connect-PnPOnline.md
- documentation/Register-PnPAzureADApp.md
- documentation/Register-PnPEntraIDAppForInteractiveLogin.md
- src/Commands/AzureAD/RegisterAzureADApp.cs
- src/Commands/AzureAD/RegisterEntraIDAppForInteractiveLogin.cs
- src/Commands/Base/ConnectOnline.cs
- src/Commands/Utilities/AzureAuthHelper.cs
Fixes #3717
Improves App creation process for Custom Azure environments as well as Connect
> Fix #3717: improvements to EntraID app creation and Connect for custom Azure env

- src/Commands/Pages/ExportPage.cs
Fixes #4193
Improve error message for non-existent page
> Fix #4193: improve error message for non-existent page

- documentation/New-PnPLibraryFileVersionBatchDeleteJob.md
Updated docs with the optional parameters
Update documentation
> Update New-PnPLibraryFileVersionBatchDeleteJob.md with optional parameters

- src/Commands/Base/GetAccessToken.cs
- src/Commands/Base/PnPAzureManagementApiCmdlet.cs
- src/Commands/Base/TokenHandler.cs
- src/Commands/Utilities/Auth/ARMEndpoint.cs
Fixes #4210
Improve token fetch
Improve ARM fetch
Improve Azure Workload Identity fetch
> Fix #4210: improve code for token fetch in cert auth

- src/Commands/Base/PnPConnection.cs
Fixes #4230
Fix incorrect clientId set in the PnPConnection object
> Fix #4230: issue with incorrect clientId set in connection object

- src/Commands/AzureAD/AddAzureADGroupMember.cs
- src/Commands/AzureAD/GetAzureADUser.cs
- src/Commands/AzureAD/RegisterManagementShellAccess.cs
- src/Commands/Base/ConnectOnline.cs
- src/Commands/Base/RequestAccessToken.cs
- src/Commands/Provisioning/Tenant/InvokeTenantTemplate.cs
- src/Commands/Site/AddAvailableSiteClassification.cs
- src/Commands/Utilities/AzureAuthHelper.cs
NA
Refactor code to remove references to PnP Management shell app
> Refactor code to remove PnP Management shell references

- pages/index.md
> Update index.md with information about deleting the multi-tenant PnP Management Shell Entra ID app

- src/Commands/Lists/AddListItemAttachment.cs
- src/Commands/Lists/AddListItemComment.cs
- src/Commands/Lists/GetListItemAttachment.cs
- src/Commands/Lists/GetListItemComment.cs
- src/Commands/Lists/RemoveListItemComment.cs
- src/Commands/ManagementApi/GetUnifiedAuditLog.cs
- src/Commands/Microsoft365Groups/NewMicrosoft365GroupSettings.cs
- src/Commands/Pages/GetPageLikedByInformation.cs
- src/Commands/PriviledgedIdentityManagement/EnablePriviledgedIdentityManagement.cs
- src/Commands/Security/GetUnfurlLink.cs
- src/Commands/Viva/AddVivaConnectionsDashboardACE.cs
- src/Commands/Viva/GetVivaConnectionsDashboardACE.cs
- src/Commands/Viva/RemoveVivaConnectionsDashboardACE.cs
- src/Commands/Viva/SetVivaConnectionsDashboardACE.cs
> Fix: New-PnPGroupSetting runtime issue and removed awaiter from code where possible

- src/Commands/Resources/GraphPermissions.json
Fixes #4173
Added permissions for selected ops
> Fix #4173 : added additional permissions for selected permission operations

- documentation/Register-PnPAzureADApp.md
- documentation/Register-PnPEntraIDAppForInteractiveLogin.md
- src/Commands/AzureAD/RegisterAzureADApp.cs
- src/Commands/AzureAD/RegisterEntraIDAppForInteractiveLogin.cs
- src/Commands/Enums/EntraIDAccountType.cs
> Feature: add ability to create EntraID apps which can be multi-tenant

- src/Commands/Base/PnPConnection.cs
- src/Commands/Utilities/BrowserHelper.cs
> Fix DeviceLogin not working with LaunchBrowser parameter

- src/Commands/AzureAD/RegisterAzureADApp.cs
- src/Commands/AzureAD/RegisterEntraIDAppForInteractiveLogin.cs
Simplify the parameter handling in the RegisterAzureADApp and RegisterEntraIDAppForInteractiveLogin commands. Remove the unnecessary ParameterSetName for the LaunchBrowser parameter. This change improves code readability and maintainability.
Fixes #4299
> Refactor AzureAD app registration commands

- src/Commands/Navigation/AddNavigationNode.cs
> feat: use of MenuState for all NavigationTypes

- CHANGELOG.md
- src/Commands/Files/RemoveFile.cs
- src/Commands/Files/RenameFile.cs
- src/Commands/Files/SetFileCheckedIn.cs
- src/Commands/Files/SetFileCheckedOut.cs
- src/Commands/Files/UndoFileCheckedOut.cs
- src/Commands/Principals/ExportUserInfo.cs
- src/Commands/UserProfiles/ExportUserProfile.cs
- src/Commands/UserProfiles/RemoveUserProfile.cs
> Refactor File cmdlets to use PnP Core SDK, improved user profile cmdlets connections

- src/Commands/Base/ConnectOnline.cs
- src/Commands/ContentTypes/AddContentType.cs
- src/Commands/ContentTypes/AddContentTypeToList.cs
- src/Commands/ContentTypes/RemoveContentType.cs
- src/Commands/ContentTypes/RemoveContentTypeFromList.cs
- src/Commands/Features/DisableFeature.cs
- src/Commands/Features/EnableFeature.cs
- src/Commands/InformationManagement/GetLabel.cs
- src/Commands/Model/PowerPlatform/PowerApp/PowerAppProperties.cs
- src/Commands/Model/Teams/TeamsChannelFilesFolder.cs
> Refactor code to use PnPCore for Features and Content Types where

- src/Commands/Base/PipeBinds/TaxonomyTermPipeBind.cs
- src/Commands/Taxonomy/ExportTaxonomy.cs
Fixes #4437
Fix GetTerm to throw proper error message
Use retry in export-pnptaxonomy
> Fix GetTerm method to throw proper error message, use retry in export-taxonomy

- documentation/Register-PnPAzureADApp.md
- documentation/Register-PnPEntraIDAppForInteractiveLogin.md
> Fix #4434: add documentation for AzureEnv parameter in cmdlets

- src/Commands/Taxonomy/GetTerm.cs
Fixes #468
Fixed code to retrieve term from a parent term
> Fix #468: Refactor GetTerm method to properly load child terms and retrieve a specific term by ID or name

- src/Commands/Graph/RemoveAvailableSiteClassification.cs
- src/Commands/Principals/RemoveUser.cs
Mentioned in #3517
Remove confirm switch , use Force to make it consistent with other cmdlets
> Feature: Remove confirm switch in favor of Force parameter to make it consistent

- documentation/Remove-PnPAvailableSiteClassification.md
- documentation/Remove-PnPUser.md
- src/Commands/Admin/NewSdnProvider.cs
- src/Commands/Admin/RemoveExternalUser.cs
- src/Commands/Admin/RemoveSdnProvider.cs
- src/Commands/Admin/RepairSite.cs
- src/Commands/Admin/RevokeUserSession.cs
- src/Commands/Admin/SetHomeSite.cs
- src/Commands/Admin/SetSiteArchiveState.cs
- src/Commands/Admin/TestSite.cs
- src/Commands/Apps/ApproveTenantServicePrincipalPermissionRequest.cs
- src/Commands/Apps/DenyTenantServicePrincipalPermissionRequest.cs
- src/Commands/Apps/DisableTenantServicePrincipal.cs
- src/Commands/Apps/EnableTenantServicePrincipal.cs
- src/Commands/Apps/RevokeTenantServicePrincipalPermission.cs
- src/Commands/AzureAD/RemoveAzureADApp.cs
- src/Commands/Base/InvokeBatch.cs
- src/Commands/Events/RemoveEventReceiver.cs
- src/Commands/Planner/RemovePlannerBucket.cs
- src/Commands/Planner/RemovePlannerPlan.cs
- src/Commands/PowerPlatform/PowerApps/ExportPowerApp.cs
- src/Commands/PowerPlatform/PowerAutomate/ExportFlow.cs
- src/Commands/PowerPlatform/PowerAutomate/RemoveFlow.cs
- src/Commands/PowerPlatform/PowerAutomate/RemoveFlowOwner.cs
- src/Commands/Principals/RemoveAlert.cs
- src/Commands/Principals/RemoveSiteGroup.cs
- src/Commands/Provider/SPOProxy/SPOProxyImplementation.cs
- src/Commands/Provisioning/Site/ConvertSiteTemplateToMarkdown.cs
- src/Commands/Taxonomy/RemoveTerm.cs
- src/Commands/Taxonomy/RemoveTermLabel.cs
> Feature #3517: Refactor code to use confirm message

- CHANGELOG.md
- documentation/Set-PnPTenant.md
- src/Commands/Admin/SetTenant.cs
- src/Commands/Model/SPOTenant.cs
N/A
Adding `-AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled` to `Set-PnPTenant`
> Adding `-AllowWebPropertyBagUpdateWhenDenyAddAndCustomizePagesIsEnabled` to `Set-PnPTenant`

- .github/workflows/buildpr.yml
- src/Commands/PnP.PowerShell.csproj
> Bump DLLs for security fixes

- pages/articles/microsoftsearch.md
Just added a section/Tip about using PnP Modern Search as an alternative to out of the box Search
> added tips about using PnP Modern Search

- CHANGELOG.md
- MIGRATE-2.0-to-3.0.md
- src/Commands/Navigation/RemoveNavigationNode.cs
- src/Commands/Security/GetFileSharingLink.cs
- src/Commands/Teams/AddTeamsChannel.cs
> Refactor navigation node and sharing links commands to remove obsolete parameters and improve code clarity

- CHANGELOG.md
- documentation/Send-PnPMail.md
- src/Commands/Base/PipeBinds/FilePipeBind.cs
- src/Commands/Utilities/MailUtility.cs
- src/Commands/Utilities/SendMail.cs
Fixes #3195
Support for referencing files from SharePoint as attachments
> Feature #3195: Refactor FilePipeBind and MailUtility to improve file handling and update documentation for email attachments

- src/Commands/PnP.PowerShell.csproj
> Fix PR builds

- src/Commands/PriviledgedIdentityManagement/EnablePriviledgedIdentityManagement.cs
- src/Commands/PriviledgedIdentityManagement/GetPriviledgedIdentityManagementEligibleAssignment.cs
- src/Commands/PriviledgedIdentityManagement/GetPriviledgedIdentityManagementRole.cs
> Refactor Privileged Identity Management cmdlets to update permission attributes and reorder using directives

- CHANGELOG.md
- documentation/Remove-PnPPropertyBagValue.md
- documentation/Set-PnPPropertyBagValue.md
- src/Commands/Web/RemovePropertyBagValue.cs
- src/Commands/Web/SetPropertyBagValue.cs
> Refactor property bag commands to use PnPAdminCmdlet and handle no-script site scenarios

- src/Commands/Base/PnPConnection.cs
Added token caching for Interactive, DeviceLogin and Creds methods
NA
Added token caching for the different auth methods
> Refactor authentication handling to integrate MSAL token caching

- src/Commands/Base/PnPConnection.cs
> Add directory creation for MSAL token cache if it doesn't exist

- documentation/Get-PnPRetentionLabel.md
- documentation/Get-PnPTenantRetentionLabel.md
Fixes #4599
The aim is to perform a fixup in doc that now wrongly show documentation for PnPTenantRetentionLabel
> Fixes the PnPRetentionLabel and PnPTenantRetentionLabel docs. Fixes #4599

- CHANGELOG.md
- documentation/Remove-PnPUserProfilePhoto.md
- documentation/Set-PnPUserProfilePhoto.md
- src/Commands/UserProfiles/RemoveUserProfilePhoto.cs
- src/Commands/UserProfiles/SetUserProfilePhoto.cs
- src/Commands/Utilities/Microsoft365GroupsUtility.cs
> Add Set-PnPUserProfilePhoto and Remove-PnPUserProfilePhoto cmdlets for user profile photo management

- documentation/Get-PnPVivaEngageCommunity.md
- documentation/New-PnPVivaEngageCommunity.md
- documentation/Remove-PnPVivaEngageCommunity.md
- src/Commands/Model/VivaEngage/VivaEngageCommunity.cs
- src/Commands/Utilities/REST/ApiRequestHelper.cs
- src/Commands/Viva/GetVivaEngageCommunity.cs
- src/Commands/Viva/NewVivaEngageCommunity.cs
- src/Commands/Viva/RemoveVivaEngageCommunity.cs
NA
Added cmdlets to handle Viva engage communities
> Add cmdlets for managing Viva Engage communities: Get-PnPVivaEngageCommunity and Remove-PnPVivaEngageCommunity

- documentation/Remove-PnPTeamsUser.md
- src/Commands/Teams/RemoveTeamsUser.cs
- src/Commands/Utilities/TeamsUtility.cs
Fixes #4624
Added support to bulk remove users from the team
> Feature: Add support for removing multiple users from a Teams team

- src/Commands/Utilities/Microsoft365GroupsUtility.cs
- src/Commands/Utilities/TeamsUtility.cs
> Refactor: Simplify POST request handling in Microsoft365GroupsUtility and TeamsUtility

- CHANGELOG.md
- documentation/Get-PnPTenant.md
- src/Commands/Admin/GetTenant.cs
- src/Commands/Attributes/CsomToModelConverter.cs
- src/Commands/Model/SPOTenant.cs
N/A
Changed `Get-PnPTenant` to generic retrieval of properties and using nullable types instead of using hardcoded defaults in the case of an exception
> Changed `Get-PnPTenant` to generic retrieval of properties and using nullable types

- src/Commands/PnP.PowerShell.csproj
> Feature: bump MSAL to latest one

- pages/articles/registerapplication.md
Link was broken to the authentication page
The link to connecting.md was invalid so changed it to authentication.md
> Fixed broken link in article

- CHANGELOG.md
- documentation/Get-PnPMicrosoft365Roadmap.md
- src/Commands/Model/ServiceHealth/Microsoft365RoadmapItem.cs
- src/Commands/Model/ServiceHealth/Microsoft365RoadmapTag.cs
- src/Commands/Model/ServiceHealth/Microsoft365RoadmapTagsContainer.cs
- src/Commands/ServiceHealth/GetMicrosoft365Roadmap.cs
N/A
Added `Get-PnPMicrosoft365Roadmap` cmdlet which allows retrieval of the items on the Microsoft 365 roadmap
> Added `Get-PnPMicrosoft365Roadmap` cmdlet

- src/Commands/PnP.PowerShell.csproj
> Bump MSAL to 4.69

- CHANGELOG.md
- src/Commands/Search/SubmitSearchQuery.cs
Fixes https://github.com/pnp/powershell/issues/4758
Fixes `-RetryCount` parameter being ignored with `Submit-PnPSearchQuery`
> Fixes `-RetryCount` parameter being ignored with `Submit-PnPSearchQuery`

- .vscode/launch.json
- CHANGELOG.md
N/A
Cleaning up and structuring launch profiles for VS Code
> Cleaning up and structuring launch profiles for VS Code

- CHANGELOG.md
- documentation/Copy-PnPPage.md
- documentation/Get-PnPPageCopyProgress.md
- documentation/Move-PnPPage.md
- src/Commands/Admin/CopyPage.cs
- src/Commands/Admin/GetPageCopyProgress.cs
- src/Commands/Admin/MovePage.cs
N/A
Added `Copy-PnPPage`, `Move-PnPPage` and `Get-PnPPageCopyProgress` cmdlets to allow for copying and moving site pages between sites
> Added `Copy-PnPPage`, `Move-PnPPage` and `Get-PnPPageCopyProgress` cmdlets

- src/Commands/PnP.PowerShell.csproj
> Fix resx again maybe

- src/Commands/PnP.PowerShell.csproj
> Maybe fix resx issue

- src/Commands/PnP.PowerShell.csproj
> Additional prop for embed resources

- src/Commands/Utilities/ListItemHelper.cs
Fixes #4875
Fix multichoice issue maybe ?
> Enhance ListItemHelper to support various input types for choices in SetFieldValues method

- src/Commands/Base/PipeBinds/TeamsTeamPipeBind.cs
Fixes #4727
Fix encoding issue with getting teams
> Fix URL encoding for displayName and mailNickname in TeamsTeamPipeBind

- src/Commands/Navigation/AddNavigationNode.cs
Fixes #4726
Add support for hash tag in URLs to support URL fragments
> Add support for special URLs in navigation node cmdlet

- src/Commands/Apps/AddApp.cs
- src/Commands/Apps/PublishApp.cs
- src/Commands/Apps/RemoveApp.cs
- src/Commands/Apps/UnpublishApp.cs
- src/Commands/Utilities/REST/ApiRequestHelper.cs
Fixes #4751
Fix app catalog related issues.
> Refactor app management commands to handle no-script site scenarios and improve error handling

- src/Commands/PnP.PowerShell.csproj
> Bump MSAL.NET to latest

- src/Commands/Base/TokenHandler.cs
> Improved logging for fetching access token

- src/Commands/Model/SPOTenant.cs
> Refactor SPOTenant class: remove unused using directive and add new properties for security group management and sensitivity labels
